### PR TITLE
FIX: conda forge should depend on tagging and pushing up a tag

### PR DESCRIPTION
**Pull request by CJ-Wright**

### CODE REVIEW

**Comment by scopatz** [comment]
Thanks for putting this in @CJ-Wright. The test you changed is now failing...

**Comment by CJ-Wright** [comment]
It seems that the test is annoyed that we don't have `push-tag` in the DAG. Can we still run this test when we depend on pushing something to gh?

**Comment by scopatz** [comment]
That seems like a bug, and PushTag should be in the DAG.

**Comment by CJ-Wright** [comment]
@scopatz ready to go! (rebase fixed things)

**Comment by scopatz** [comment]
Thanks @CJ-Wright!

**Pull request merged**
