### PR TITLE
fixing sphinx behavior

### PR DESCRIPTION
**Pull request by rjkoch**
changed `doc_configurable` flag in `docs/conf.py` to `is_configurable`

### CODE REVIEW

**Comment by rjkoch** [comment]
changed `doc_store_as_str `flag in` docs/conf.py` to `can_store_as_str`

**Comment by rjkoch** [comment]
@CJ-Wright  This successfully resolves the issues with Travis failing in [this ](https://github.com/regro/rever/pull/245)PR.

This failure was additionally holding up the release, I didn't see it because the pytest activity was failing (this is now fixed) and the pytest activity runs before the sphinx activity.

**Review by CJ-Wright — APPROVED** [review]
LGTM

**Comment by CJ-Wright** [comment]
Thank you!
I am making this comment solely in my personal capacity and am not conveying any rights to any intellectual property of any third parties.

**Pull request merged**
