### PR TITLE
initialization

### PR DESCRIPTION
**Pull request by scopatz**

### CODE REVIEW

**Comment by mariusvniekerk** [comment]
LGTM?

This seems to be failing on sphinx things?

**Comment by gforsyth** [comment]
Seems like the `conda_forge` activity expects `github3.py` to be installed but it isn't be default: https://github.com/regro/rever/blob/master/rever/activities/conda_forge.xsh#L6

**Comment by scopatz** [comment]
Good eye @gforsyth! Hopefully this fixes it!

**Comment by mariusvniekerk** [comment]
```
>       del builtins.__xonsh_env__['YOU_DONT']
E       AttributeError: __delitem__
```

**Comment by scopatz** [comment]
Oh interesting, I guess our deprecation proxies aren't dispatching delitem

**Pull request merged**
