### PR TITLE
AppImage Activity

### PR DESCRIPTION
**Pull request by anki-code**
Rever AppImage activity is used to add xonsh AppImage - https://github.com/xonsh/xonsh/pull/3559

### CODE REVIEW

**Comment by anki-code** [comment]
fyi @niess

**Comment by anki-code** [comment]
Can anybody merge this?
@scopatz @CJ-Wright @asmeurer

**Comment by CJ-Wright** [comment]
Can you provide a bit more context here? What is AppImage?

**Comment by anki-code** [comment]
**AppImage** is a format for distributing portable software on Linux without needing superuser permissions to install the application. It tries also to allow Linux distribution-agnostic binary software deployment for application developers, also called Upstream packaging.

In short AppImage is a single file that contain the app and it could be run on any Linux.

More info:
* https://en.wikipedia.org/wiki/AppImage
* https://appimage.org/

**Comment by CJ-Wright** [comment]
Would it be possible to have tests for this?

**Comment by anki-code** [comment]
@CJ-Wright Test added:
```
$ pytest tests/test_appimage.py
tests/test_appimage.py::test_appimage PASSED [100%]

================================================================================ 1 passed in 58.60s ================================================================================
```

**Comment by anki-code** [comment]
@CJ-Wright is it enough?

**Comment by anki-code** [comment]
Any news here?

**Comment by CJ-Wright** [comment]
Thank you for your patience!

**Pull request merged**
