### PR TITLE
replace None syntax with * <add entry> (with no API breakage)

### PR DESCRIPTION
**Pull request by CJ-Wright**
move from ``None`` to ``* <add entry>`` news syntax.

### CODE REVIEW

**Comment by CJ-Wright** [comment]
@scopatz ready for review!
@jakirkham I hope this syntax is a bit more understandable for the news entries.

**Comment by scopatz** [comment]
Not to wordsmith this to death, but can you think of a phrase you'd prefer over "add entry" @jakirkham?

**Comment by jakirkham** [comment]
Naming is hard. 😅 IDK "(add) item"? Happy to defer if something speaks to you.

**Comment by scopatz** [comment]
maybe "news item"?

**Comment by jakirkham** [comment]
Yeah, "news item" SGTM.

**Comment by CJ-Wright** [comment]
ready for merge/review

**Comment by scopatz** [comment]
Thanks @CJ-Wright! I guess it is time to run `rever setup` everywhere...

**Pull request merged**
