### PR TITLE
rever requires xonsh & lazyasd

### PR DESCRIPTION
**Pull request by takluyver**
So declare the dependencies in setup.py.

Also, regarding the comment about `console_scripts`: it's fine if you install with pip (`pip install .` to install locally). It only does the problematic setuptools thing if setuptools does the installation without pip supervising.

### CODE REVIEW

**Comment by CJ-Wright** [comment]
These are the reqs I think: https://github.com/conda-forge/rever-feedstock/blob/master/recipe/meta.yaml#L22

**Comment by takluyver** [comment]
Thanks, I've copied that list.

Out of interest, do you really see startup times < 0.1 s? Running `time rever --help` on my machine is consistently giving me about 3 seconds.

**Comment by CJ-Wright** [comment]
That text was most likely copied from the `xonsh` setup.py, since startup times are really important for shells.

**Comment by takluyver** [comment]
ah, that makes more sense.

**Comment by scopatz** [comment]
And yeah, rever's startup times are pretty slow for some reason.  I haven't looked into it, yet though

**Pull request merged**
