### PR TITLE
NO_COLOR -> RESET fix

### PR DESCRIPTION
**Pull request by scopatz**

### CODE REVIEW

**Comment by scopatz** [comment]
Ready for review CC @CJ-Wright @mariusvniekerk

**Comment by CJ-Wright** [comment]
Did you get a chance to look at this locally?

**Comment by scopatz** [comment]
No, was planning on doing a release with this to get rever back to having no deprecation warnings with the latest xonsh

**Comment by CJ-Wright** [comment]
ahh ok

**Comment by scopatz** [comment]
Seems like it worked!

**Pull request merged**
