### PR TITLE
Add custom_forge activity

### PR DESCRIPTION
**Pull request by hadim**
~~Because of https://github.com/regro/rever/issues/217#issuecomment-672870363, this PR is against `0.4.3`.~~

A new activity called `custom_forge` is added to allow people to update a feedstock from a custom and/or private conda-forge.

I have created a new activity instead of patching the existing `conda_forge` one because:

- I needed to be able to push directly in the `master` branch of the `upstream` feedstock.
  - _I know it's not necessarily a good practice but we do it internally with our private forge (we only manage a dozens of packages so fixing CI errors manually is fine)._

- Our forge uses `git_url` instead of `url` so we don't need to hash an URL.
  - _I also know this is not a good practice but our forge has been setup that way._

I am also fine merging this activity with the `conda_forge` one if you prefer.

Here are the default settings of the activity (different from `conda_forge):

```bash
$CUSTOM_FORGE_FEEDSTOCK = None
$CUSTOM_FORGE_PROTOCOL = 'ssh'
$CUSTOM_FORGE_SOURCE_URL = None
$CUSTOM_FORGE_HASH_TYPE = 'sha256'
$CUSTOM_FORGE_PULL_REQUEST = False
$CUSTOM_FORGE_RERENDER = True
$CUSTOM_FORGE_FEEDSTOCK_ORG = 'invivoai-forge'
$CUSTOM_FORGE_FORK = False
$CUSTOM_FORGE_FORK_ORG = ''
$CUSTOM_FORGE_USE_GIT_URL = True

$CUSTOM_FORGE_PATTERNS = (
    ('meta.yaml', '  version:\\s*[A-Za-z0-9._-]+', '  version: "$VERSION"'),
    (
        'meta.yaml',
        '{% set version = ".*" %}',
        '{% set version = "$VERSION" %}',
    ),
    ('meta.yaml', '  number:.*', '  number: 0'),
)
```

### CODE REVIEW

**Comment by scopatz** [comment]
Hey @hadim! I am totally in favor of the custom forge idea here.  It looks like you just copied a lot of the conda-forge code though.  Is there any way you can split some of this out of both activites and maybe get some code reuse? 

Also maybe it would be good to just have a "forge" activity from which the conda-forge and/or custom forge could be specializations of.

**Comment by hadim** [comment]
Do you prefer to have a single "forge" activity where a user can configure conda-forge or custom forge using configuration variables or do you prefer to have two distinct activities as it is now (with as much as possible common code refactored)?

**Comment by scopatz** [comment]
I prefer a single forge activity, with a subclass that specializes on conda-forge, so that existing rever.xsh files aren't broken.

**Comment by hadim** [comment]
Sorry, this is still not clear to me @scopatz :-D

We keep the `conda_forge` activity as it is in terms of user-facing API. I create a `forge` activity that will be the parent class of the `CondaForge` activity (called `Forge` for example). That way we end up with two activities (`forge` and `conda_forge`) + two classes + factorized code + full backward compatibility.

Is that what you mean?

**Comment by scopatz** [comment]
Sorry for being unclear! Yeah that is exactly what I mean. I think you get it :wink:

**Comment by hadim** [comment]
Thanks @scopatz. Will do that in the coming days/weeks.

I have a quick question related to rever in general. What is the reason it's based on xonsh?

**Comment by scopatz** [comment]
There are a couple of reasons: 

1. rever needs to run a lot of subcommand
2. configuration through the environment makes sense for something like this
3. I wanted to write a full project in xonsh

**Comment by scopatz** [comment]
People should feel free to submit new modules and things in Python if that makes sense though too

**Comment by scopatz** [comment]
This looks great, thanks

**Comment by hadim** [comment]
Besides the unit tests, I haven't manually tested the conda forge activity. I would suggest you do it before releasing a new version.

**Comment by scopatz** [comment]
Yeah, releasing rever will test that?

**Comment by hadim** [comment]
Ahaha good one :-D

**Comment by scopatz** [comment]
Tried it on xonsh, seems like it works https://github.com/conda-forge/xonsh-feedstock/pull/149

**Pull request merged**
