### PR TITLE
GHRELEASE_TARGET

### PR DESCRIPTION
**Pull request by scopatz**
Potential fix for #237

### CODE REVIEW

**Review by kcpevey — APPROVED** [review]
Confirmed this works for me! Thanks!

**Comment by asmeurer** [comment]
Shouldn't it use the default branch from the repo by default? That requires the API to get, but that shouldn't be an issue for an action that is about uploading a release.

**Comment by scopatz** [comment]
Yeah, that is better, @asmeurer

**Comment by scopatz** [comment]
Updated!

**Comment by hadim** [comment]
The same kind of fix could also be applied to the forge activity.

**Comment by hadim** [comment]
@rjkoch do you think that could be merged too?

**Comment by rjkoch** [comment]
LGTM, bit new to this myself, @CJ-Wright what do you think? could be part of the next release...

**Comment by CJ-Wright** [comment]
LGTM, I didn't realize GH had a default branch concept.

I am making this comment solely in my personal capacity and am not conveying any rights to any intellectual property of any third parties.

@rjkoch please feel free to merge!

**Comment by CJ-Wright** [comment]
(Note you may need to walk back some of the partially finished release so these changes can be let in)
I am making this comment solely in my personal capacity and am not conveying any rights to any intellectual property of any third parties.

**Pull request merged**
