### PR TITLE
change order

### PR DESCRIPTION
**Pull request by scopatz**
not sure how this got past CI, no need for news

### CODE REVIEW

**Comment by CJ-Wright** [comment]
oops sorry that review didn't catch it either

**Comment by scopatz** [comment]
It seems like all Travis is doing is building docs?

**Comment by CJ-Wright** [comment]
Sounds about right (does doctr support the other CIs yet?)

**Comment by asmeurer** [comment]
No but PRs welcome. I haven't had much time to work on doctr as of late.

**Comment by scopatz** [comment]
I think this is because we were on circle 1.0 for the actual tests

**Comment by scopatz** [comment]
CI is back!

**Pull request merged**
