### PR TITLE
version key entry test

### PR DESCRIPTION
**Pull request by scopatz**
minor fix to make command run on old rever/ dirs that might be hanging around

### CODE REVIEW

**Comment by scopatz** [comment]
CC @CJ-Wright  @justcalamari

**Comment by CJ-Wright** [comment]
Would it be possible to have a test?

**Comment by scopatz** [comment]
It is being tested, since this function is hit a lot, esp in `test_main`. This specificaly handles the default mode where `'version'` is present in the history.  The case where version is not present is deprecate, and so it is probably not worth testing it excessively, since to do so we would have to reproduce deprecated behavior.

**Comment by CJ-Wright** [comment]
Ah ok :+1:

**Pull request merged**
