### PR TITLE
Docker Activities

### PR DESCRIPTION
**Pull request by scopatz**
Adds docker activities for building and pushing custom docker containers

### CODE REVIEW

**Comment by scopatz** [comment]
CC @CJ-Wright - this is needed for libcflib

**Comment by CJ-Wright** [comment]
LGTM, why is this needed for libcflib?

**Comment by scopatz** [comment]
I am trying to get rever to be able to deploy the REST API when a new version is released.

**Comment by CJ-Wright** [comment]
That's awesome!

**Comment by CJ-Wright** [comment]
Let me know when you are ready for more review/merge.

**Comment by scopatz** [comment]
I think it is ready:)

**Comment by CJ-Wright** [comment]
awesome!

**Pull request merged**
