### PR TITLE
ENH: use rever's tarball for the GitHub url for conda-forge

### LINKED ISSUE #137: Rever should use its own tarballs for conda-forge
Now that we are making tarballs, we might as well use them as the source url for the conda forge activity. This also nicely sidesteps the whole issue about GH moving the shas around on its own tarballs.

### PR DESCRIPTION
**Pull request by CJ-Wright**
closes #137

### CODE REVIEW

**Comment by scopatz** [comment]
Thanks @CJ-Wright! The tests are failing with this change,

**Comment by scopatz** [comment]
Also, I think that this is not sophisticated enough.  Basically, it should be the file that we upload *if* we upload a file.  Otherwise, it should be the original URL that is the download link that GitHub provides, which is guaranteed to be there.

**Comment by CJ-Wright** [comment]
We most likely should just do the same thing the bot does, which is update the version number and read the meta.yaml to get the new url. This way it will work for packages which get their tarballs from PyPI.

**Comment by scopatz** [comment]
Thanks @CJ-Wright!

**Pull request merged**
